version: '3'

volumes:
  postgres_volume:

services:
  auth:
    image: auth:${APP_IMAGE_TAG}
    container_name: auth
    env_file:
      - ${ENV}.env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
  db:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: db
    env_file:
      - ${ENV}.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  migrator:
    image: migrator:${MIGRATOR_IMAGE_TAG}
    container_name: migrator
    restart: on-failure
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy