version: '3'

volumes:
  postgres_volume:

services:
  # auth:
    # image: auth:1.0.0
    # environment:
    # ports:
    #   - "${AUTH_PORT}:50000"
  pg:
    image: postgres:16.2-alpine3.19
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  # migrator:
  #   image: migrator:1.0.0
  #   restart: on-failure
  #   environment:
  #     DB_HOST: pg
